FROM ubuntu:jammy-20240911.1

ARG APP_VERSION

ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /usr

RUN apt-get update \
    && apt-get install -y --no-install-recommends curl git cmake build-essential \
    autoconf automake libtool pkg-config libglpk-dev cmake libnng-dev openjdk-17-jre \ 
    libmbedtls-dev liblzma-dev libbz2-dev libxrender1 libxtst6 libxi6 \
    && curl -fsSLO https://github.com/CompEvol/beast2/releases/download/${APP_VERSION}/BEAST.${APP_VERSION}.Linux.x86.tgz \
    && tar fxz BEAST.${APP_VERSION}.Linux.x86.tgz \
    && rm BEAST.${APP_VERSION}.Linux.x86.tgz \
    && mv beast /usr/bin \
    && git clone --depth=1 https://github.com/beagle-dev/beagle-lib.git \
    && cd beagle-lib \
    && mkdir build \
    && cd build \
    && cmake -DBUILD_SSE=OFF -DBUILD=_CUDA=OFF .. \
    && make install \
    && ldconfig \
    && cd /usr \
    && rm -rf beagle-lib \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/downloaded_packages \
    && chmod -R +x /usr/bin 

ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

WORKDIR /usr/bin/beast

EXPOSE 5900