version: "3.9"

services:

  beast2:
    image: ghcr.io/jbris/beast2:${APP_VERSION}
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.${APP_VERSION}
      args:
        APP_VERSION: $APP_VERSION
        BEAGLE_VERSION: $BEAGLE_VERSION
        TRACER_VERSION: $TRACER_VERSION
    working_dir: /usr/local/workspace
    ports:
      - 5900:5900
    volumes:
      - ./workspace:/usr/local/workspace:rwx
